### ISSUE TITLE
New methods request for `Chapters` and `SubFile`

### ISSUE THREAD

**Issue by PhosCity** [Jaded-Encoding-Thaumaturgy/muxtools#12]
I have a couple of feature requests. If they already exist and I missed them in the docs, let me know.

- In [Chapters.from_sub](https://muxtools.vodes.pw/muxtools/chapters/#muxtools.misc.chapters.Chapters.from_sub), could you add two more parameters:
    - `use_actor_field` which makes this method search for chapter marker in actor instead of effect field.
    - `marker` so that we can use any chapter marker we want and not just `chapter` or `chptr`.
- In [SubFile](https://muxtools.vodes.pw/muxtools/subtitle/sub/#muxtools.subtitle.sub.SubFile), could you add two more paramaters:
    - `clean_extradata` which removes extradata form the subtitle file.
    - `remove_comments` which removes all commented lines from the subtitle file.
- This is optional request and may be more high effort than others so feel free to ignore it if you wish to. This maybe a method for `Premux` or `mux`, I'm quite not sure.
Essentially, I want a way to edit the metadata of tracks in the mkv. 
Let's say I have a video, japanese audio and german audio. No matter what their order are, let's say I want a way to set video to track order 1, name it to "[choom/MTBB Encode]" + set japanese audio to track order 2, name it to "Japanese", set it's default to yes + set german audio to track order 3, name it to "German", set it's default to no.
I don't know what it'd look like. Maybe 
```python
Premux.video(lang="jpn", default=True, track_order=0, name="[choom/MTBB Encode]").audio(
    jpn={"name": "Japanese", "default": "True", "track_order": 1},
    de={"name": "German", "default": "False", "track_order": 2},
)
```
If the audio does not exist, ignore it of course.

**Comment by PhosCity** [comment]
Currently my workaround (which is probably bad in many ways) for the optional feature request is:
```python
    video_id = utils.find_tracks(
        video_file_path,
        type=utils.types.TrackType.VIDEO,
    )[0].track_id

    audio_tracks = utils.find_tracks(
        sub_properties["video"], type=utils.types.TrackType.AUDIO
    )

    for track in audio_tracks:
        if track.language == "ja":
            japanese_audio_id = track.track_id
        elif track.language == "en":
            english_audio_id = track.track_id

    if "english_audio_id" not in locals():
        english_audio_id = None

    if not english_audio_id:
        mkvmerge_args = f'--no-global-tags --track-name {japanese_audio_id}:"Japanese" --default-track-flag {japanese_audio_id}:yes --track-order 0:{video_id},0:{japanese_audio_id}'
    else:
        mkvmerge_args = f'--no-global-tags --track-name {japanese_audio_id}:"Japanese" --default-track-flag {japanese_audio_id}:yes --track-name {english_audio_id}:"English" --default-track-flag {english_audio_id}:no --track-order 0:{video_id},0:{japanese_audio_id},0:{english_audio_id}'

    video = Premux(
        video_file_path,
        subtitles=None,
        keep_attachments=False,
        mkvmerge_args=mkvmerge_args,
    )
```

**Comment by Vodes** [comment]
Yeah I wouldn't mind adding the sub and chapter stuff.

I'm also not really against the premux stuff but I wouldn't expect that in a timely manner. I don't really need it and I've been kinda busy lately so the priority is low.

**Comment by PhosCity** [comment]
Awesome!

And it's understandable about the premux feature. The workaround seems to be working in the limited testing I've done so I'll use that for the time being.

**Comment by Vodes** [comment]
Added the sub and chapter stuff. Feel free to test.
If everything works I'll probably release a new patch version because the fontcollector changes are also quite useful.

**Comment by PhosCity** [comment]
I tested it briefly and all four of the features seems to work properly. Thanks!
